### PR TITLE
[Docs] Update README to include manual validation example

### PR DESCRIPTION
**Pull request by patricklindsay**
Since upgrading a couple of my forms broke as the manually validation steps have changed.

I couldn't find an example in the README so added one. Hopefully saves people searching through the source or old issues.

### CODE REVIEW

**Comment by tagliala** [comment]
@patricklindsay thanks

We have a wiki page covering manual triggering of validations: https://github.com/DavyJonesLocker/client_side_validations/wiki/Manually-trigger-input-validation

It is good to specify that validations will be automatically fired, but I don't want to add how to manual trigger them because that should not be necessary in the default use case.

**Comment by patricklindsay** [comment]
Agree, it's not necessary in the default use case however their are plenty of use cases where people will want to do this. Having the example in a wiki is useful but it's easily missed (like I did).

Could remove it from the usage section and move it further down the README?

**Comment by tagliala** [comment]
> plenty of use cases where people will want to do this.

Any example?

There is another common use case, such as validate dinamically added forms, but it still has its own wiki

> Could remove it from the usage section and move it further down the README?

I like the "Your form will now automatically validate when it is submitted." part in the usage section.

I would like to avoid the snippet of code because it will probably lead to cut & paste.

Another section could be fine, I would like to start with a small real world use case as an introduction to that behaviour.

**Comment by patricklindsay** [comment]
Two example use cases would be;
- A multi step form - Validate the form before allowing user to move to the next step
- Partial forms within a modal or tab - The form validates before allowing the user to navigate away (switch tab or close modal) 

How about adding a section further down the README such as;

## Manual Validation
If for some reason you would like to manually validate the form (for example you're working with a multi-step form);

```js
form = $('form')
validators = form[0].ClientSideValidations.settings.validators
form.isValid(validators)
```
_Note: Default behaviour will automatically validate the form._

-----
If that doesn't suit you no problem, I'll just close the PR.

**Comment by tagliala** [comment]
@patricklindsay thanks.

What do you think about:

> ## Manual validation ##
> 
> By default, ClientSideValidations will automatically validate the form.
> 
> If for some reason you would like to manually validate the form (for example you're working with a multi-step form):
> 
> ```js
> $input     = $('#myInputField');
> $form      = $input.closest('form');
> validators = $form[0].ClientSideValidations.settings.validators;
> 
> // Validate a single field
> $input.isValid(validators);
> 
> // Validate the whole form
> $form.isValid(validators);
> ```
> 
> It might not work for multiple inputs selected at once by `$input`.
> 
> To manually validate a single field, you may also trigger a focusout event:
> 
> ```js
> $('#myInputField').trigger('focusout');
> ```

?

**Comment by patricklindsay** [comment]
Looks good! Want me to add it underneath usage section?

**Comment by tagliala** [comment]
@patricklindsay thanks, did that by myself

Closed via 08c4158

**Pull request closed without merging**
