### PR TITLE
preventing undesired stopPropagation on focusout event

### PR DESCRIPTION
**Pull request by akelmanson**
it happens when isValid() == false

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks. Could this be an issue also for some other event?

**Comment by akelmanson** [comment]
It might be. If you want, I can modify the other events.

**Comment by tagliala** [comment]
> It might be. If you want, I can modify the other events.
Add your review

Yes, please

**Comment by akelmanson** [comment]
Done!

**Comment by tagliala** [comment]
I can squash commits automatically, did you run `rake test:js` to check that everything is fine?

**Comment by akelmanson** [comment]
Tested on chrome and got the same 4 errors I've got with v4.2.6.

**Comment by tagliala** [comment]
which browser? everything is fine on chrome 53 / OSX 10.12

**Comment by akelmanson** [comment]
test_js

**Pull request merged**
