### PR TITLE
fixed issue of removing error message 

### PR DESCRIPTION
**Pull request by adityashankert**
if there are more than 2 classes for error field div class then if the error message is displayed it will not go if the user corrects the field

### CODE REVIEW

**Comment by tagliala** [comment]
Hi,

thanks for this PR but there are a couple of issues:

1. You should edit the [coffee file](https://github.com/DavyJonesLocker/client_side_validations/blob/master/coffeescript/rails.validations.coffee) and recompile the javascript via `rake regenerate_javascript`
2. You should add a failing unit test that your PR is going to fix, or give me hints so I can reproduce the bug and make a proper test

Let me know if you need further assistance

**Comment by adityashankert** [comment]
Hi,

I don't know how to write tests i can tell you to reproduce it can you write the tests? i will do the coffee script thing and create a new pull request will it do?

**Comment by adityashankert** [comment]
I am closing this pull request and will raise new one

**Comment by tagliala** [comment]
@adityashankert yes, tell me how to reproduce I will try to write a failing unit test

**Comment by adityashankert** [comment]
@tagliala https://github.com/DavyJonesLocker/client_side_validations/pull/608 check this new pull request I have written the reproduction steps there.

**Pull request closed without merging**
