### PR TITLE
Choices for select should be an optional parameter

### PR DESCRIPTION
**Pull request by v-kumar**
When using select in block mode, choices need not be passed. For example, thoughtbot/administrate uses select tag helper as follows. Consistently reproducible when using with administrate.

So, I made choices an optional parameter with default nil.

```
ActionView::Template::Error (wrong number of arguments (given 1, expected 2..4)):
    20:   <%= f.label field.permitted_attribute %>
    21: </div>
    22: <div class="field-unit__field">
    23:   <%= f.select(field.permitted_attribute) do %>
    24:     <%= options_for_select(field.associated_resource_options, field.selected_option) %>
    25:   <% end %>
    26: </div>
  client_side_validations (4.2.4) lib/client_side_validations/action_view/form_builder.rb:71:in `select_with_client_side_validations'
```

I am quoting rails source code here and you can see that `choices` is optional. So, made `select_with_client_side_validations` consistent with the original `without` counterpart.

```
# File actionview/lib/action_view/helpers/form_options_helper.rb, line 162
def select(object, method, choices = nil, options = {}, html_options = {}, &block)
  Tags::Select.new(object, method, self, choices, options, html_options, &block).render
end
```

### CODE REVIEW

**Comment by tagliala** [comment]
:+1: 

I will probably do this in another commit

**Comment by tagliala** [comment]
@v-kumar #665

There are also other old signatures inherited from Rails 2-3 (e.g: fields_for). I'm going to check them all

BTW Rails 4.0 does not allow a block and the signature is correct for that version of Rails. Anyway, I'm going to make them consistent with 4.2 and check if they work with previous versions

**Comment by tagliala** [comment]
@v-kumar please give a try to v4.2.5

**Comment by v-kumar** [comment]
@tagliala Works. Thanks for promptly acting on my request.

**Pull request closed without merging**
