### PR TITLE
Resolving issue 619

### PR DESCRIPTION
**Pull request by alekseyl**
https://github.com/DavyJonesLocker/client_side_validations/issues/619

repair broken logic of conditional validation.

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks!

Although this makes sense, I need a failing spec test which deals with this case

Could you please edit this PR?

**Comment by tagliala** [comment]
(current failures are not depending on your PR, I'm taking a look to see what happened)

**Comment by tagliala** [comment]
@alekseyl there are failing specs, do you mind to take a look and add another spec that shows your issue?

**Comment by alekseyl** [comment]
>@alekseyl there are failing specs, do you mind to take a look and add another spec that shows your issue?

Yeap I'll try

**Comment by alekseyl** [comment]
I think those specs are failing because that conditions never ran before :), so I think there no need to create new specs, just make that three looks good.

**Comment by tagliala** [comment]
@alekseyl there are specs failing... could you please take a look?

**Comment by alekseyl** [comment]
yeap I saw that they are still broken, I'll try to fix them, but I can't promise to make it fast, lot's of work :( sorry

**Comment by tagliala** [comment]
I will take a look. #623 is caused by this broken logic?

**Comment by alekseyl** [comment]
Yea, conditional validations works only if they using "_changed?" methods.

**Comment by tagliala** [comment]
@alekseyl I need a failing test and a more detailed explanation of this issue

**Pull request closed without merging**
