### PR TITLE
Adding missing block param to select_with(out)_client_side_validation…

### PR DESCRIPTION
**Pull request by thenadz**
This addresses the issue described in #621.

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks but I also need a test showing the issue before merging

I would also check other methods, if they need blocks

**Comment by thenadz** [comment]
Ok. I'll work on getting that test for you.

This was the only select_* method that took a block from the FB methods. I didn't look at the others in detail, but I can take another look.

**Comment by tagliala** [comment]
I should also add:
* http://apidock.com/rails/v4.0.2/ActionView/Helpers/FormBuilder/collection_radio_buttons
* http://apidock.com/rails/v4.0.2/ActionView/Helpers/FormBuilder/collection_check_boxes

They both receive a block as a parameter

I'm opening another issue

**Comment by tagliala** [comment]
@thenadz merged, thanks. I will take care of the tests

**Comment by thenadz** [comment]
Fantastic! Thanks for getting this in so quickly.

**Pull request merged**
