### PR TITLE
Change gemspec to match version of Rails 5.0

### PR DESCRIPTION
**Pull request by SebDE**

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks for this PR, I'm going to address this by myself.

You should also edit `.travis.yml` and `Appraisals`

**Comment by tagliala** [comment]
Actually I was checking if it is possible to make the gem compatible from 4.0.0 to 5.1.0

**Comment by SebDE** [comment]
I understand - I tested the gem with rails 5.0.0.beta1:
I see the following two things:
>DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in included at /Users/sebastian/.rvm/gems/ruby-2.3.0@rails5.0/bundler/gems/client_side_validations-84544e3ac1ce/lib/client_side_validations/action_view/form_builder.rb:19)

and

>GET http://localhost:3000/validators/uniqueness?case_sensitive=false&organisation%5Bcompany%5D=test&_=1452634553071 500 (Internal Server Error)

if I use the uniqueness validator ... 
The other functions of the gem are full functional without problems for the moment

**Comment by tagliala** [comment]
> I understand - I tested the gem with rails 5.0.0.beta1:

There are a lot of failing tests at the moment, did you try `rake test` ?

**Comment by tagliala** [comment]
Moreover,

```
Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 1.6.4)

  In Gemfile:
    client_side_validations was resolved to 5.0.0, which depends on
      rails (< 5.1.0, >= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
        actionpack (= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
          rack (~> 2.x)

    sinatra (~> 1.4) was resolved to 1.4.6, which depends on
      rack-protection (~> 1.4) was resolved to 1.5.3, which depends on
        rack

    shotgun (~> 0.9.1) was resolved to 0.9.1, which depends on
      rack (>= 1.0)

    sinatra (~> 1.4) was resolved to 1.4.6, which depends on
      rack (~> 1.4)

    thin (~> 1.6) was resolved to 1.6.4, which depends on
      rack (~> 1.0)
```

This gem rely on sinatra for unit tests, so a deep rewrite is needed. At the moment there are no sinatra/shotgun gems ready for rack 2.0.0.alpha1

**Comment by tagliala** [comment]
@SebDE 

Please update your rails5 branch. All specs pass but I'm still using `alias_method_chain` because switching to `Module#prepend` is not straightforward

Let's continue here: #645

:lock:

**Pull request closed without merging**
