### PR TITLE
Removing removal of whitespace from generated regex.

### PR DESCRIPTION
**Pull request by thenadz**
This addresses the whitespace regex issue described in the response to #615.

I'm happy to develop tests for this issue also, but I first need to understand some of the logic in this this monkey patch. The first 3 replacements make sense, but after that I'm at a loss for why they need to be removed. It's also possible that the removal of white space was included for a reason, in which case some compromise will need to be found that doesn't kill valid regexes...

### CODE REVIEW

**Comment by thenadz** [comment]
Regarding `test_multiline_regexp_as_json`, why would removing new lines be the valid behavior..? I could see replacing the new line literal with `\n`, but the current behavior completely changes the regex meaning. I would think the below is the correct test:

    def test_multiline_regexp_as_json
      test_regexp = /
      /
      expected_regexp = { source: '\n    ', options: '' }
      assert_equal expected_regexp, test_regexp.as_json
    end

**Comment by tagliala** [comment]
Relevant commit: https://github.com/DavyJonesLocker/client_side_validations/commit/94edd8064851678ba4e07556dc0c1e023cda7e1d

Relevant pull request: https://github.com/DavyJonesLocker/client_side_validations/pull/390

**Comment by tagliala** [comment]
I understand that there is a problem with whitespace, but other whitespace characters should be stripped out

**Comment by tagliala** [comment]
http://ruby-doc.org/core-1.9.3/Regexp.html

> `/\s/` - A whitespace character: `/[ \t\r\n\f]/`

I would go for `[\t\r\n\f]`

**Comment by thenadz** [comment]
Interesting. Thanks for tracking down the related information. I'll push up something to strip all but " " from the whitespace character group and update the related test accordingly.

**Comment by tagliala** [comment]
Thanks

We may also need a js unit test

**Comment by thenadz** [comment]
The changes I just pushed up ended up also adding support for Regex::EXTENDED. It doesn't arrive at JS w/ an actual equivalent option (so `test_regexp_modifiers_as_json` is still valid), but rather is just postprocessing the regex to strip *all* whitespace (same as old behavior) when `x` option is set.

If you can point me to the location in the JS unit tests where the requested test(s) would be, I'm happy to give it a go. I'm a bit lost on the JS side tbh.

**Comment by janosch-x** [comment]
This solution is not quite right for two reasons:

1. In extended mode, it will remove *escaped* whitespace, which does have a matching function:
r = /\ /x # r matches spaces, but r.source.sub(/\s/, '') returns '\\'

2. In normal mode (without option /x), it will remove literal tabs, carriage returns, newlines and form feeds, which DO have a matching function:
r = /
/ # r matches newlines, but r.source.sub(/\n/, '') returns ''

A correct solution will have to do the following:

a) remove all *non-escaped* whitespace in extended mode.
b) turn literal tabs, carriage returns, newlines and form feeds into escape sequences - \t, \r, \n, \f - whether /x is set or not. (JavaScript's new RegExp() constructor expands escape sequences, so when using that, \\t, \\r, \\n, \\f are needed).

I'll post a solution shortly.

**Comment by tagliala** [comment]
Fixed via #637

**Pull request closed without merging**
